XX <- model.matrix(shuryo~hinshu, data=soy)
soy <- read.table("soybeans.txt", sep=",", header=TRUE)
XX <- model.matrix(shuryo~hinshu, data=soy)
t(XX) %*% soy$shuryo/apply(XX,2,sum)
lm.result <- lm(shuryo~hinshu, data=soy)
summary(lm.result)
sum((soy$shuryo-mean(soy$shuryo))^2)
sum(lm.result$residuals^2)
1-pf(sum((soy$shuryo-mean(soy$shuryo))^2) / 5 / (sum(lm.result$residuals^2) / 18), 5, 18)

source("solderbalance.txt")
plot.design(solder.balance)
aovresult <- aov(skips~., data=solder.balance)
summary(aovresult)
qf(0.99,2,702)
qf(0.99,1,702)
qf(0.99,3,702)
qf(0.99,9,702)
qf(0.99,2,702)

la <- aov(shuryo~., data=soy)
summary(la)
qf(0.99,2,18)
